services:
  twitch-miner:
    image: ghcr.io/fueledbyredbull/twitch-miner-rust:latest
    platform: linux/arm/v7
    init: true
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      TCPM_CONFIG: /data/config.json
      TCPM_DATA_DIR: /data
    volumes:
      - ./data:/data
