name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - "**/*.md"

jobs:
  rust-qa:
    permissions:
      contents: read
    uses: ./.github/workflows/rust-qa.yml
